name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Latest stable version

      - name: Set up Python
        uses: actions/setup-python@v4  # Latest stable version
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r event_registration/ -f json -o bandit_report.json
          cat bandit_report.json
        continue-on-error: true  # Allow the pipeline to continue even if Bandit finds issues

      - name: Check Bandit Report
        run: |
          if grep -q '"issue":' bandit_report.json; then
            echo "Security issues found in the code."
            exit 1  # Exit with an error if issues are found
          else
            echo "No security issues found."
          fi